### ISSUE TITLE
Markbot Issue

### ISSUE THREAD

**Issue by amberlbailey** [amberlbailey/typographic-insets#1]
@thomasjbradley

So it all started when it said it wasn't online. I asked Sara and she said she updated her computer and it worked. I updated and it's now online but now I have a new issue.

Markbot is having an issue finding the status of the repository. It's saying that there is no commits, but there are. Everything is synced and committed but its still giving me these errors and I don't know how to fix them.

<img width="799" alt="screen shot 2016-11-03 at 3 19 41 pm" src="https://cloud.githubusercontent.com/assets/22101703/19981725/773f2d68-a1d9-11e6-9a5d-d49c8bd12e5f.png">

**Comment by thomasjbradley** [comment]
So you updated to MacOS Sierra?

**Comment by thomasjbradley** [comment]
If so, you'll have to reinstall the command line tools—step 13:
https://learn-the-web.algonquindesign.ca/courses/web-dev-1/install-all-the-things/#step-13

**Comment by amberlbailey** [comment]
Thanks!
